version: "3.7"
services:
  postgres:
    image: postgres:11-alpine
    container_name: pg
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=TestStore
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
